package com.haero_kim.keepit.util

object ShoppingMallList {
    val shoppingMallList: Map<String, String> = mapOf(
        "gsshop" to "GS SHOP",
        "hmall" to "현대 Hmall",
        "akmall" to "AK mall",
        "lotteon" to "롯데 ON",
        "lotteimall" to "롯데홈쇼핑",
        "cjmall" to "CJmall",
        "nsmall" to "NS 홈쇼핑",
        "elotte" to "롯데백화점",
        "coupang" to "쿠팡",
        "tmon" to "티몬",
        "11st" to "11번가",
        "musinsa" to "무신사",
        "halfclub" to "하프클럽",
        "wconcept" to "W컨셉",
        "elandmall" to "이랜드몰",
        "29cm" to "29CM",
        "stylenanda" to "스타일난다",
        "lfmall" to "LFmall",
        "ssfshop" to "SSF샵",
        "fashionplus" to "패션플러스",
        "nike" to "나이키",
        "adidas" to "아디다스",
        "a-bly" to "에이블리",
        "converse" to "컨버스",
        "wemakeprice" to "위메프",
        "gmarket" to "G마켓",
        "auction" to "옥션",
        "ebay" to "이베이",
        "interpark" to "인터파크",
        "amazon" to "아마존",
        "aliexpress" to "알리익스프레스",
        "chuu" to "츄",
        "smartstore" to "스마트스토어",
        "apple" to "애플",
        "samsung" to "삼성"
    )
}